### ISSUE TITLE
Error on startpage : apc_fcntl_create

### ISSUE THREAD

**Issue by mcraz** [ajessup/laravel#1]
`Symfony \ Component \ Debug \ Exception \ FatalErrorException`
`PHP Startup: apc_fcntl_create: could not open C:\Windows\.apc.a02884`

The stacktrace shows only

```
1. Symfony\Component\Debug\Exception\FatalErrorException
Unknown0
0. Illuminate\Exception\Handler handleShutdown
<#unknown>0
```

**Comment by ajessup** [comment]
Is this running on App Engine or elsewhere?

**Comment by mcraz** [comment]
GAE PHP sdk for windows. But, its long fixed now. Tx !
